dist: focal
language: python
python:
  - "3.8"
  - "3.9"
  - "3.10"


install:
  - pip install -r requirements.txt


script:
  - python -m unittest discover -s tests -p "*.py"


deploy:
  provider: pypi
  username: __token__
  password: $PYPI_TOKEN
  on:
    tags: true
    branch: master
    python: "3.9"
